stages:
    - test
    - compile

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/

before_script:
    - npm install --save-dev

test_job:
    stage: test
    script:
      - npm run test
    tags:
      - master
      - dev

build_job:
    stage: compile
    script:
      - npm run build
    tags:
      - master

test_ci_push:
  tags:
    - master
  stage: profiling
  allow_failure: false
  script:
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@jaxlab.asuscomm.com:30000/mcf/crud.git &> /dev/null
    - touch test.data
    - echo "This is a test" > test.dat
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git add --all
    - git commit -m "GitLab Runner Push"
    - git push http://${YOUR_USERNAME}:${PERSONAL_ACCESS_TOKEN}@jaxlab.asuscomm.com:30000/mcf/crud.git HEAD:master