stages:
    - test
    - build
    
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/

test_job:
    stage: test
    script:
    - npm install --save-dev
    - npm run test
    tags:
    - master

build_job:
    stage: build
    script:
    - npm install --save-dev
    - npm run build
    tags:
    - master
