stages:
    - test
    - compile

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/

before_script:
    - npm install --save-dev

test_job:
    stage: test
    script:
      - npm run test
    coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'
    tags:
      - master
      - develop
    

build_job:
    stage: compile
    script:
      - npm run build
    tags:
      - master
      - develop